// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-nkNR_MWUm0IQ65OzODhukKThzulVdVA',
    appId: '1:755420009959:web:ee4918e1a1f6823e8ed942',
    messagingSenderId: '755420009959',
    projectId: 'uwielbiajmy-go',
    authDomain: 'uwielbiajmy-go.firebaseapp.com',
    storageBucket: 'uwielbiajmy-go.appspot.com',
    measurementId: 'G-GLLRCTLQ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-B-EM9RYVJVT_oDlYePN54qnXFUnXdZo',
    appId: '1:755420009959:android:db07fbe4921e4f3c8ed942',
    messagingSenderId: '755420009959',
    projectId: 'uwielbiajmy-go',
    storageBucket: 'uwielbiajmy-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnOlzUOK30MXMYZe57WK4eeRek7BTefY',
    appId: '1:755420009959:ios:c247bd8f63613f118ed942',
    messagingSenderId: '755420009959',
    projectId: 'uwielbiajmy-go',
    storageBucket: 'uwielbiajmy-go.appspot.com',
    iosBundleId: 'com.example.uwielbiajmyGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnOlzUOK30MXMYZe57WK4eeRek7BTefY',
    appId: '1:755420009959:ios:f796cc06e3b2b8a38ed942',
    messagingSenderId: '755420009959',
    projectId: 'uwielbiajmy-go',
    storageBucket: 'uwielbiajmy-go.appspot.com',
    iosBundleId: 'com.example.uwielbiajmyGo.RunnerTests',
  );
}
